# -*- coding: utf-8 -*-
"""Generate 30 test day files for A2plus with grammar, vocab, phrase questions."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TESTS = ROOT / "content" / "A2plus" / "tests"


def compute_id(question: str, options: list[str], correct_index: int) -> str:
    payload = question + "|" + "|".join(options) + "|" + str(correct_index)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]


def q(question: str, options: list[str], correct_index: int,
      explanation: str, related_rule_ids: list[str]) -> dict:
    return {
        "id": compute_id(question, options, correct_index),
        "question": question,
        "options": options,
        "correctIndex": correct_index,
        "explanation": explanation,
        "relatedRuleIds": related_rule_ids,
    }


# ─── DAY 01: feeling-good + true-love ───────────────────────────────
DAY01 = [
    # feeling-good — Question forms
    q("Which sentence is a correct yes/no question?",
      ["You do like jazz?", "Do you like jazz?", "Like you jazz?", "You like jazz?"],
      1, "'Do you like jazz?' — yes/no questions use do/does + subject + verb.", ["feeling-good"]),
    q("Choose the correct subject question:",
      ["Who does live here?", "Who lives here?", "Who do live here?", "Who here lives?"],
      1, "'Who lives here?' — when who is the subject, no auxiliary verb needed.", ["feeling-good"]),
    q("Complete the question: 'What ___ at the weekend?'",
      ["do you usually do", "you usually do", "do you usually", "usually do you"],
      0, "'What do you usually do at the weekend?' — wh- + do + subject + verb.", ["feeling-good"]),
    q("Choose the correct sentence with a preposition at the end:",
      ["About what are you talking?", "What are you talking about?", "What you are talking about?", "You are talking about what?"],
      1, "'What are you talking about?' — prepositions stay at the end in questions.", ["feeling-good"]),
    # feeling-good — vocabulary
    q("What does 'hang out with friends' mean?",
      ["расслабляться", "тусоваться с друзьями", "ходить в кино", "читать книгу"],
      1, "'Hang out with friends' means 'тусоваться с друзьями'.", ["feeling-good"]),
    q("Complete: 'We decided to ___ and watch a film.'",
      ["stay in", "go shopping", "do nothing", "relax"],
      0, "'Stay in' means 'оставаться дома'.", ["feeling-good"]),
    # true-love — Past simple
    q("Which sentence uses the past simple correctly?",
      ["I didn't went to the party.", "I didn't go to the party.", "I not went to the party.", "I didn't going to the party."],
      1, "'I didn't go' — after didn't, the verb is in base form (no -ed).", ["true-love"]),
    q("Choose the correct past simple form: 'She ___ to Paris last year.'",
      ["go", "goed", "went", "gone"],
      2, "'Went' is the past simple of 'go'.", ["true-love"]),
    q("Complete the question: '___ you fall in love at first sight?'",
      ["Do", "Does", "Did", "Are"],
      2, "'Did you fall in love?' — past simple question uses 'did' + base verb.", ["true-love"]),
    q("Choose the correct negative sentence:",
      ["She didn't want to go on a second date.", "She didn't wanted to go.", "She not wanted to go.", "She didn't wants to go."],
      0, "'She didn't want' — correct past simple negative.", ["true-love"]),
    # true-love — vocabulary
    q("Which word completes the sentence? 'We got ___ in a small village church.'",
      ["marry", "married", "marriage", "marrying"],
      1, "'Got married' — the correct past form of 'get married'.", ["true-love"]),
    q("Choose the correct collocation: 'I ___ my wife at university.'",
      ["met", "meeted", "knowed", "saw"],
      0, "'Met' is the past simple of 'meet'.", ["true-love"]),
]

# ─── DAY 02: nice-day + the-company-4u ─────────────────────────────
DAY02 = [
    # nice-day — Present simple vs present continuous
    q("Which sentence is correct?",
      ["I work from nine to five every day.", "I am working from nine to five every day.", "I working from nine to five.", "I works from nine to five."],
      0, "Present simple for routines: 'I work from nine to five every day.'", ["nice-day"]),
    q("Complete: 'She is usually cheerful, but today she ___ a bit grumpy.'",
      ["feels", "is feeling", "feel", "feeling"],
      1, "'Is feeling' — present continuous for what's happening today/unusually.", ["nice-day"]),
    q("Choose the correct pair: 'Water ___ at 100 degrees. I ___ coffee right now.'",
      ["boils / am drinking", "is boiling / drink", "boil / am drinking", "is boiling / am drinking"],
      0, "'Boils' is a fact (present simple). 'Am drinking' is happening now (present continuous).", ["nice-day"]),
    q("Which sentence is a correct present simple question?",
      ["Are you work here?", "Do you work here?", "You work here?", "Working you here?"],
      1, "'Do you work here?' — present simple question with 'do'.", ["nice-day"]),
    # nice-day — vocabulary
    q("What does 'do nothing' mean?",
      ["делать домашнее задание", "ничего не делать", "расслабляться", "читать книгу"],
      1, "'Do nothing' means 'ничего не делать'.", ["nice-day"]),
    q("Complete: 'Let's go ___ a walk in the park.'",
      ["to", "for", "on", "at"],
      1, "'Go for a walk' — fixed collocation.", ["nice-day"]),
    # the-company-4u — State verbs
    q("Which sentence is INCORRECT?",
      ["I am knowing the answer.", "I know the answer.", "She wants a new job.", "He loves his work."],
      0, "'Know' is a state verb — 'I am knowing' is incorrect.", ["the-company-4u"]),
    q("Choose the correct sentence:",
      ["I am thinking about your offer.", "I am thinking you are right.", "I think about your offer right now.", "I am think about your offer."],
      0, "'Am thinking' as a process of considering is correct. 'Think' as an opinion uses present simple.", ["the-company-4u"]),
    q("Complete: 'This ___ to the company.'",
      ["is belonging", "belongs", "belong", "is belong"],
      1, "'Belongs' — state verb, not used in continuous.", ["the-company-4u"]),
    q("Which sentence uses a state verb correctly?",
      ["I am needing a coffee.", "She is having lunch with a client today.", "He is understanding the problem.", "They are wanting a new car."],
      1, "'Is having lunch' — 'have' as an action can be continuous. State verbs: need, understand, want.", ["the-company-4u"]),
    # the-company-4u — vocabulary
    q("Choose the correct collocation: 'Please don't ___ a noise — the baby is sleeping.'",
      ["do", "make", "have", "take"],
      1, "'Make a noise' — fixed collocation with 'make'.", ["the-company-4u", "hidden-talent"]),
    q("Complete: 'Could you ___ me a favour?'",
      ["do", "make", "have", "give"],
      0, "'Do someone a favour' — fixed collocation.", ["the-company-4u", "hidden-talent"]),
]

# ─── DAY 03: risky-business + like-working-outside ──────────────────
DAY03 = [
    # risky-business — Adverbs of frequency
    q("Choose the correct sentence:",
      ["I always arrive before 8 a.m.", "I arrive always before 8 a.m.", "Always I arrive before 8 a.m.", "I arrive before always 8 a.m."],
      0, "'Always' goes before the main verb 'arrive'.", ["risky-business"]),
    q("Complete: 'She ___ rarely stressed because she plans everything.'",
      ["is", "does", "has", "rarely is"],
      0, "Adverbs of frequency go AFTER the verb 'to be' — 'she is rarely'.", ["risky-business"]),
    q("Put the adverb in the correct place: 'I ___ work at weekends.' (don't often)",
      ["don't often work", "don't work often", "often don't work", "work don't often"],
      0, "In negatives, 'often' goes after the auxiliary 'don't'.", ["risky-business"]),
    q("Which adverb means 'almost never'?",
      ["usually", "often", "hardly ever", "sometimes"],
      2, "'Hardly ever' means 5% — almost never.", ["risky-business"]),
    # risky-business — vocabulary
    q("Complete: 'A sales rep usually ___ a lot for work.'",
      ["travel", "travels", "travelling", "travelled"],
      1, "'Travels' — third person singular in present simple.", ["risky-business"]),
    q("Which phrase means 'работать удалённо'?",
      ["work outdoors", "work remotely", "work full-time", "work part-time"],
      1, "'Work remotely' means 'работать удалённо'.", ["risky-business"]),
    # like-working-outside — Expressing likes and dislikes
    q("Complete the sentence: 'I love ___ outside when the weather is nice.'",
      ["work", "working", "worked", "to working"],
      1, "After 'love', use the -ing form: 'love working'.", ["like-working-outside"]),
    q("Which sentence means you are neutral about something?",
      ["I love commuting.", "I don't mind commuting.", "I can't stand commuting.", "I hate commuting."],
      1, "'Don't mind' is neutral — you're not against it.", ["like-working-outside"]),
    q("Choose the correct translation: 'I can't stand working in an open-plan office.'",
      ["Обожаю работать в опенспейсе.", "Терпеть не могу работать в опенспейсе.", "Не против работать в опенспейсе.", "Люблю работать в опенспейсе."],
      1, "'Can't stand' means 'терпеть не могу'.", ["like-working-outside"]),
    q("Complete: 'Do you like ___ in the fashion industry?'",
      ["work", "working", "worked", "to working"],
      1, "After 'like' in questions, use -ing form: 'Do you like working'.", ["like-working-outside"]),
    # like-working-outside — idioms
    q("What does 'not my cup of tea' mean?",
      ["это не мой чай", "не моё, не по душе", "очень люблю", "в самый раз"],
      1, "'Not my cup of tea' means 'не моё, не по душе'.", ["like-working-outside"]),
    q("Complete: 'I could never do a ___ job — I need flexibility.'",
      ["nine-to-five", "five-to-nine", "nine-to-nine", "part-time"],
      0, "'A nine-to-five job' means a regular office job from 9 a.m. to 5 p.m.", ["like-working-outside"]),
]

# ─── DAY 04: free-in-nyc + relax ───────────────────────────────────
DAY04 = [
    # free-in-nyc — Future: present continuous & be going to
    q("Which sentence describes a definite arrangement (tickets booked)?",
      ["I am going sightseeing tomorrow — I've booked a tour.", "I am going to go sightseeing someday.", "I will go sightseeing.", "I might go sightseeing."],
      0, "Present continuous ('am going') with a specific arrangement indicates a definite plan.", ["free-in-nyc"]),
    q("Complete: 'We ___ to have a picnic in Central Park this Sunday.'",
      ["are going", "go", "will going", "are go"],
      0, "'Are going to' + verb — intention/plan.", ["free-in-nyc"]),
    q("Choose the correct sentence for a future arrangement:",
      ["I am flying to New York on Friday morning.", "I fly to New York on Friday morning.", "I am fly to New York.", "I will flying to New York."],
      0, "Present continuous ('am flying') with a specific time = confirmed arrangement.", ["free-in-nyc"]),
    q("Complete the question: '___ you seeing the show tonight?'",
      ["Do", "Are", "Will", "Is"],
      1, "'Are you seeing' — present continuous for a planned event.", ["free-in-nyc"]),
    # free-in-nyc — vocabulary
    q("What does 'go sightseeing' mean?",
      ["ходить в кино", "осматривать достопримечательности", "заниматься спортом", "гулять по парку"],
      1, "'Go sightseeing' means 'осматривать достопримечательности'.", ["free-in-nyc"]),
    q("Complete: 'The museum is free on Sundays — it won't cost you a ___.'",
      ["dime", "penny", "cent", "pound"],
      1, "'Not cost a penny' — an expression meaning it's free.", ["free-in-nyc"]),
    # relax — Questions without auxiliaries (subject questions)
    q("Which is a correct subject question?",
      ["Who wants to go to the art gallery?", "Who does want to go?", "Who do want to go?", "Who wants go?"],
      0, "'Who wants' — who is the subject, so no auxiliary needed.", ["relax"]),
    q("Choose the correct question: '___ happened at the skate park yesterday?'",
      ["What did", "What", "What was", "What does"],
      1, "'What happened' — what is the subject, no auxiliary needed.", ["relax"]),
    q("Which is an object question?",
      ["Who called you?", "Who lives here?", "What happened?", "Who organised the concert?"],
      0, "'Who called you?' — could be either, but here 'who' is the subject calling. Actually 'Who did you call?' would be object. Let me check: 'Who called you?' — who = subject. 'Who did you call?' — who = object.", ["relax"]),
    q("What's the difference? 'Who wrote this?' vs 'Who did you write to?'",
      ["Both are subject questions.", "First is subject, second is object question.", "First is object, second is subject.", "Both are incorrect."],
      1, "'Who wrote this?' — who is the subject. 'Who did you write to?' — who is the object.", ["relax"]),
    # relax — vocabulary
    q("Which phrase means 'how you spend your free time'?",
      ["work hours", "time out", "rush hour", "overtime"],
      1, "'Time out' means free time / leisure time.", ["relax"]),
    q("Complete: 'Which bus ___ to the botanical garden?'",
      ["does go", "goes", "go", "going"],
      1, "Subject question: 'Which bus goes' — bus is the subject, so no auxiliary.", ["relax"]),
]

# ─── DAY 05: can-i-take-a-message + hidden-talent ──────────────────
DAY05 = [
    # can-i-take-a-message — Phone calls
    q("How do you introduce yourself on the phone?",
      ["I am Anna.", "Here is Anna.", "This is Anna speaking.", "Anna here is."],
      2, "'This is Anna speaking' — the correct phone introduction.", ["can-i-take-a-message"]),
    q("Complete: 'Could I ___ to Mr Jones, please?'",
      ["talk", "speak", "say", "tell"],
      1, "'Could I speak to...' — the standard polite request on the phone.", ["can-i-take-a-message"]),
    q("What does 'I'll put you through' mean?",
      ["Я перезвоню", "Я соединю вас", "Я положу трубку", "Я запишу"],
      1, "'I'll put you through' means 'я соединю вас'.", ["can-i-take-a-message"]),
    q("Complete the message: 'Could you ask him to ___ me back?'",
      ["phone", "call", "ring", "speak"],
      1, "'Call me back' — the most common phrase for returning a call.", ["can-i-take-a-message"]),
    # can-i-take-a-message — vocabulary
    q("What does 'hold on' mean on the phone?",
      ["повесить трубку", "подождать", "перезвонить", "записать"],
      1, "'Hold on' means 'подождать (не вешать трубку)'.", ["can-i-take-a-message"]),
    q("Complete: 'He's in a ___ right now. Can I take a message?'",
      ["talk", "meeting", "call", "work"],
      1, "'In a meeting' — the most common reason someone isn't available.", ["can-i-take-a-message"]),
    # hidden-talent — Present perfect with ever/never
    q("Complete: '___ you ever performed on stage?'",
      ["Do", "Did", "Have", "Are"],
      2, "'Have you ever...' — present perfect for life experience.", ["hidden-talent"]),
    q("Choose the correct sentence:",
      ["I have never sung in public.", "I haven't never sung in public.", "I didn't never sing.", "I have never sang."],
      0, "'I have never sung' — one negative (never), correct past participle (sung).", ["hidden-talent"]),
    q("Complete: 'She ___ never flown in a helicopter before.'",
      ["has", "have", "is", "does"],
      0, "'Has never flown' — third person singular + present perfect.", ["hidden-talent"]),
    q("Which question asks about life experience?",
      ["Where did you go yesterday?", "Have you ever eaten sushi?", "Do you like pizza?", "Will you go tomorrow?"],
      1, "'Have you ever...' asks about life experience up to now.", ["hidden-talent"]),
    # hidden-talent — vocabulary (make/do collocations)
    q("Complete: 'I need to ___ a decision about which course to take.'",
      ["do", "make", "have", "take"],
      1, "'Make a decision' — fixed collocation.", ["hidden-talent"]),
    q("Choose the correct collocation: 'I always ___ my homework in the evening.'",
      ["make", "do", "have", "take"],
      1, "'Do homework' — fixed collocation.", ["hidden-talent"]),
]

# ─── DAY 06: schools-of-thought + what-should-i-do ─────────────────
DAY06 = [
    # schools-of-thought — can, have to, must
    q("Complete: 'You ___ wear a uniform at this school.'",
      ["can", "have to", "mustn't", "don't have to"],
      1, "'Have to' — obligation due to rules.", ["schools-of-thought"]),
    q("Which sentence expresses a strong prohibition?",
      ["You can't eat in class.", "You mustn't use your phone during the exam.", "You don't have to go.", "You can borrow books."],
      1, "'Mustn't' is a strong prohibition — 'запрещено'.", ["schools-of-thought"]),
    q("What's the difference between 'mustn't' and 'don't have to'?",
      ["They mean the same thing.", "'Mustn't' is prohibition, 'don't have to' means no obligation.", "'Mustn't' is no obligation, 'don't have to' is prohibition.", "Both mean no obligation."],
      1, "'Mustn't' = запрещено. 'Don't have to' = не обязательно (no obligation).", ["schools-of-thought"]),
    q("Complete: 'We ___ go to school on Saturdays — it's optional.'",
      ["mustn't", "don't have to", "can't", "must"],
      1, "'Don't have to' — no obligation, optional.", ["schools-of-thought"]),
    # schools-of-thought — vocabulary
    q("What does 'wear a uniform' mean?",
      ["носить форму", "покупать форму", "снимать форму", "стирать форму"],
      0, "'Wear a uniform' means 'носить форму'.", ["schools-of-thought"]),
    q("Complete: 'You can borrow books from the ___ for two weeks.'",
      ["shop", "library", "school", "office"],
      1, "'Library' — where you borrow books.", ["schools-of-thought"]),
    # what-should-i-do — Giving advice
    q("Complete the advice: 'You ___ practise speaking every day.'",
      ["should", "mustn't", "don't have to", "can't"],
      0, "'Should' — giving a recommendation.", ["what-should-i-do"]),
    q("Choose the correct sentence:",
      ["You shouldn't be afraid of making mistakes.", "You should not afraid.", "You don't should be afraid.", "You shouldn't to be afraid."],
      0, "'Shouldn't be afraid' — correct negative form of 'should' + base verb.", ["what-should-i-do"]),
    q("Complete: 'Why ___ you join a language exchange group?'",
      ["do", "don't", "aren't", "not"],
      1, "'Why don't you...' — a friendly suggestion.", ["what-should-i-do"]),
    q("What does 'If I were you, I'd apologise' mean?",
      ["Я извинюсь, если ты придёшь.", "Я бы на твоём месте извинился.", "Если я буду тобой, я извинюсь.", "Ты должен извиниться."],
      1, "'If I were you, I'd...' means 'я бы на твоём месте...'.", ["what-should-i-do"]),
    # what-should-i-do — vocabulary
    q("Complete: 'You ought to try that new ___ place — the pasta is incredible!'",
      ["Italian", "Italy", "Italic", "Italian's"],
      0, "'Italian place' — an Italian restaurant.", ["what-should-i-do"]),
    q("Which phrase offers a suggestion?",
      ["You must go.", "Why don't you take a break?", "You can't go.", "I'll go."],
      1, "'Why don't you...' — a friendly suggestion.", ["what-should-i-do"]),
]

# ─── DAY 07: fantastic-film-trips + travel-tips ────────────────────
DAY07 = [
    # fantastic-film-trips — Past simple vs past continuous
    q("Complete: 'I was travelling around Italy when I ___ my best friend.'",
      ["met", "was meeting", "meet", "had met"],
      0, "Past simple ('met') for the main event that interrupted the continuous action.", ["fantastic-film-trips"]),
    q("Choose the correct sentence:",
      ["While we were driving to the coast, it started to rain heavily.", "While we drove to the coast, it was starting to rain.", "While we were driving, it was starting to rain.", "While we drove, it started to rain heavily."],
      0, "Past continuous ('were driving') for background, past simple ('started') for event.", ["fantastic-film-trips"]),
    q("Complete: 'She was sleeping on the train when the ticket inspector ___ her up.'",
      ["was waking", "woke", "wakes", "is waking"],
      1, "'Woke' — past simple for the interrupting action.", ["fantastic-film-trips"]),
    q("Which part of the sentence is the background (continuous) action? 'I was watching TV when the electricity went out.'",
      ["was watching TV", "went out", "the electricity", "I was"],
      0, "'Was watching TV' is the continuous background action.", ["fantastic-film-trips"]),
    # fantastic-film-trips — vocabulary
    q("Complete: 'While we were ___ to the coast, it started to rain.'",
      ["driving", "drive", "drove", "driven"],
      0, "'Were driving' — past continuous of 'drive'.", ["fantastic-film-trips"]),
    q("What does 'ticket inspector' mean?",
      ["кассир", "контролёр", "пилот", "водитель"],
      1, "'Ticket inspector' means 'контролёр' (in a train).", ["fantastic-film-trips"]),
    # travel-tips — Verb patterns
    q("Complete: 'I want ___ Japan next spring.'",
      ["visit", "to visit", "visiting", "visited"],
      1, "'Want to + verb' — 'want' takes the infinitive with 'to'.", ["travel-tips"]),
    q("Choose the correct sentence:",
      ["She enjoys trying local food.", "She enjoys to try local food.", "She enjoy trying local food.", "She enjoys try local food."],
      0, "'Enjoys' takes the -ing form: 'enjoys trying'.", ["travel-tips"]),
    q("Complete: 'You need ___ your hotel in advance.'",
      ["book", "to book", "booking", "booked"],
      1, "'Need to + verb' — 'need' takes the infinitive with 'to'.", ["travel-tips"]),
    q("Which verb takes the -ing form?",
      ["want", "need", "suggest", "plan"],
      2, "'Suggest' takes the -ing form: 'suggest taking'. Want, need, plan take 'to + verb'.", ["travel-tips"]),
    # travel-tips — vocabulary
    q("Complete: 'I suggest ___ a guided tour — it's worth it!'",
      ["take", "to take", "taking", "took"],
      2, "'Suggest' + -ing: 'suggest taking'.", ["travel-tips"]),
    q("What does 'book in advance' mean?",
      ["отменить бронь", "забронировать заранее", "оплатить на месте", "проверить бронь"],
      1, "'Book in advance' means 'забронировать заранее'.", ["travel-tips"]),
]

# ─── DAY 08: you-cant-miss-it + keeping-fit ────────────────────────
DAY08 = [
    # you-cant-miss-it — Directions
    q("Complete: 'Go straight ___ until you see a supermarket.'",
      ["on", "in", "to", "at"],
      0, "'Go straight on' — fixed phrase for directions.", ["you-cant-miss-it"]),
    q("Choose the correct direction:",
      ["Take the first turning on the right.", "Take the first turn on right.", "Take first turn right.", "First take turning right."],
      0, "'Take the first turning on the right' is the correct phrase.", ["you-cant-miss-it"]),
    q("What does 'You can't miss it!' mean?",
      ["Ты можешь пропустить это.", "Ты не сможешь это не заметить.", "Ты не умеешь пропускать.", "Это легко потерять."],
      1, "'You can't miss it!' means 'Ты не сможешь это не заметить / не пройдёшь мимо'.", ["you-cant-miss-it"]),
    q("Complete: 'The museum is ___ the train station.'",
      ["opposite", "on", "in", "at"],
      0, "'Opposite' — 'напротив', used for giving directions.", ["you-cant-miss-it"]),
    # you-cant-miss-it — vocabulary
    q("Complete: 'Excuse me, how do I get to the nearest ___ station?'",
      ["tube", "tunnel", "underground", "train"],
      0, "'Tube station' — London underground station.", ["you-cant-miss-it"]),
    q("What does 'cross the road' mean?",
      ["перейти дорогу", "пересечь дорогу на машине", "стоять на дороге", "смотреть на дорогу"],
      0, "'Cross the road' means 'перейти дорогу'.", ["you-cant-miss-it"]),
    # keeping-fit — Present perfect with for/since
    q("Complete: 'I've been a vegetarian ___ five years.'",
      ["since", "for", "from", "in"],
      1, "'For' + period of time (five years).", ["keeping-fit"]),
    q("Choose the correct sentence:",
      ["She's worked at this gym since 2020.", "She's worked at this gym for 2020.", "She's worked at this gym since three years.", "She's worked at this gym for she moved here."],
      0, "'Since' + specific point in time (2020). 'For' + duration.", ["keeping-fit"]),
    q("Complete: 'How long have you ___ your best friend?'",
      ["knew", "know", "known", "knowing"],
      2, "'Have you known' — past participle of 'know' is 'known'.", ["keeping-fit"]),
    q("Choose the correct word: 'I haven't seen him ___ we graduated from university.'",
      ["for", "since", "from", "ago"],
      1, "'Since' + specific event (graduation).", ["keeping-fit"]),
    # keeping-fit — vocabulary
    q("Complete: 'They've lived in this neighbourhood ___ a very long time.'",
      ["since", "for", "in", "from"],
      1, "'For' + 'a very long time' (duration).", ["keeping-fit"]),
    q("What does 'keep fit' mean?",
      ["сохранять форму", "одеваться", "готовить еду", "убираться"],
      0, "'Keep fit' means 'поддерживать спортивную форму'.", ["keeping-fit"]),
]

# ─── DAY 09: the-future-of-food + how-are-you-feeling ──────────────
DAY09 = [
    # the-future-of-food — may, might, will
    q("Which sentence expresses the highest certainty?",
      ["I might try that new restaurant.", "I may go to the party.", "I'll be 30 next year.", "Maybe I'll cook tonight."],
      2, "'Will' expresses the highest certainty (fact or strong prediction).", ["the-future-of-food"]),
    q("Complete: 'Scientists say it ___ take another decade to perfect the technology.'",
      ["will", "may", "might", "can"],
      1, "'May' — 50% possibility, appropriate for scientific uncertainty.", ["the-future-of-food"]),
    q("Choose the sentence with 'might' expressing low probability:",
      ["I might try that new vegan restaurant this weekend — I'm not sure yet.", "It will rain tomorrow.", "The sun rises in the east.", "I can swim."],
      0, "'Might' = low probability (~20-30%), uncertain.", ["the-future-of-food"]),
    q("Complete: 'I'll ___ order pizza tonight.'",
      ["probably", "maybe", "perhaps", "might"],
      0, "'Probably' goes after 'will': 'I'll probably order pizza.'", ["the-future-of-food"]),
    # the-future-of-food — vocabulary
    q("What does 'plant-based food' mean?",
      ["еда животного происхождения", "еда на растительной основе", "фаст-фуд", "замороженная еда"],
      1, "'Plant-based food' means 'еда на растительной основе'.", ["the-future-of-food"]),
    q("Complete: 'We won't solve world hunger ___, but we'll make progress.'",
      ["overnight", "daytime", "tonight", "yesterday"],
      0, "'Overnight' — 'за одну ночь' (quickly).", ["the-future-of-food"]),
    # how-are-you-feeling — Seeing the doctor
    q("Complete: 'I've got a terrible ___ and my eyes hurt.'",
      ["headache", "head hurt", "head pain", "headache pain"],
      0, "'I've got a headache' — the correct way to say 'у меня болит голова'.", ["how-are-you-feeling"]),
    q("Choose the correct sentence:",
      ["My throat hurts when I swallow.", "My throat hurt when I swallow.", "I'm throat hurts.", "My throat is hurt."],
      0, "'My throat hurts' — correct possessive + verb.", ["how-are-you-feeling"]),
    q("Complete: 'I feel ___ and I've got a high temperature.'",
      ["dizzy", "dizz", "dizziness", "dizzing"],
      0, "'I feel dizzy' — adjective after 'feel'.", ["how-are-you-feeling"]),
    q("What does the doctor ask?",
      ["How do you feel?", "What do you feel?", "How are you feel?", "What you feel?"],
      0, "'How do you feel?' is what a doctor asks.", ["how-are-you-feeling"]),
    # how-are-you-feeling — vocabulary
    q("Complete: 'He's got a bad ___ and a runny nose.'",
      ["cough", "coughing", "coughs", "cough-up"],
      0, "'A bad cough' — noun form.", ["how-are-you-feeling"]),
    q("What does 'I feel sick' mean?",
      ["Я чувствую себя больным / меня тошнит", "Я болею", "Я здоров", "Я устал"],
      0, "'I feel sick' means 'меня тошнит / я плохо себя чувствую'.", ["how-are-you-feeling"]),
]

# ─── DAY 10: living-the-dream + the-great-impostor ─────────────────
DAY10 = [
    # living-the-dream — Used to
    q("Complete: 'I ___ be afraid of the dark, but now I'm fine.'",
      ["used to", "use to", "was used to", "did use to"],
      0, "'Used to' — past habit/state that is no longer true.", ["living-the-dream"]),
    q("Choose the correct negative:",
      ["She didn't use to enjoy cooking, now she's a chef!", "She didn't used to enjoy cooking.", "She used not to enjoy.", "She used to not enjoy."],
      0, "Negative: 'didn't use to' (without 'd').", ["living-the-dream"]),
    q("Complete the question: '___ you use to have long hair?'",
      ["Did", "Do", "Used", "Have"],
      0, "Question: 'Did you use to...?' (without 'd').", ["living-the-dream"]),
    q("What does 'I used to smoke, but I quit last year' mean?",
      ["Я курю, но брошу в следующем году.", "Раньше я курил, но бросил в прошлом году.", "Я использовал сигареты.", "Я курил в прошлом году."],
      1, "'Used to' + verb means 'раньше делал, а сейчас нет'.", ["living-the-dream"]),
    # living-the-dream — vocabulary
    q("Complete: 'He used to smoke, but he ___ last year.'",
      ["quit", "quite", "quiet", "quote"],
      0, "'Quit' — past simple of 'quit' (бросил).", ["living-the-dream"]),
    q("What does 'used to' express?",
      ["привычку в настоящем", "привычку в прошлом, которой сейчас нет", "будущее намерение", "обязанность"],
      1, "'Used to' = past habit/state no longer true.", ["living-the-dream"]),
    # the-great-impostor — Purpose, cause, result
    q("Complete: 'I went to the library ___ study in peace.'",
      ["because", "to", "so", "for"],
      1, "'To' + verb expresses purpose (зачем).", ["the-great-impostor"]),
    q("Choose the correct sentence expressing cause:",
      ["She passed the exam because she worked hard.", "She passed the exam to work hard.", "She passed the exam so she worked hard.", "She passed the exam for working hard."],
      0, "'Because' gives the reason/cause.", ["the-great-impostor"]),
    q("Complete: 'He forgot his keys, ___ he couldn't get into the house.'",
      ["because", "so", "to", "so that"],
      1, "'So' introduces the result (and what happened next).", ["the-great-impostor"]),
    q("What does 'so that' express?",
      ["причину", "результат", "цель с оттенком 'чтобы'", "противопоставление"],
      2, "'So that' expresses purpose, like 'для того чтобы'.", ["the-great-impostor"]),
    # the-great-impostor — vocabulary
    q("Complete: 'I'll leave early so that I ___ miss the train.'",
      ["won't", "don't", "didn't", "wouldn't"],
      0, "'So that I won't miss' — purpose clause with future meaning.", ["the-great-impostor"]),
    q("Complete: 'The flight was cancelled because ___ the storm.'",
      ["of", "for", "from", "with"],
      0, "'Because of' + noun (the storm).", ["the-great-impostor"]),
]

# ─── DAY 11: can-you-tell-me + treasure-hunt ──────────────────────
DAY11 = [
    # can-you-tell-me — Polite questions / finding out info
    q("Complete the polite question: 'Could you tell me where the nearest bank ___?'",
      ["is", "does", "it is", "is it"],
      0, "After polite 'Could you tell me', use statement word order (no inversion).", ["can-you-tell-me"]),
    q("Choose the correct sentence:",
      ["Do you know if there's a restaurant nearby?", "Do you know is there a restaurant?", "Do you know there is a restaurant?", "Do you know if is there a restaurant?"],
      0, "'Do you know if...' + statement word order.", ["can-you-tell-me"]),
    q("Complete: 'I'd like to know what time the museum ___.'",
      ["opens", "does open", "open", "opening"],
      0, "After 'I'd like to know', use statement order: 'what time the museum opens'.", ["can-you-tell-me"]),
    q("What does 'I was wondering if you could help me' express?",
      ["a direct order", "a very polite request", "a past action", "a fact"],
      1, "'I was wondering if...' is a very polite way to ask for help.", ["can-you-tell-me"]),
    # can-you-tell-me — vocabulary
    q("Complete: 'Do you know ___ the bus arrives?'",
      ["when", "that", "what", "where"],
      0, "'When' — asking about time.", ["can-you-tell-me"]),
    q("What does 'give me a hand' mean?",
      ["дать руку", "помочь", "пожать руку", "помахать рукой"],
      1, "'Give me a hand' means 'помочь'.", ["can-you-tell-me"]),
    # treasure-hunt — Relative clauses
    q("Complete: 'He's the guy ___ helped me with my homework.'",
      ["which", "who", "whose", "where"],
      1, "'Who' for people in relative clauses.", ["treasure-hunt"]),
    q("Choose the correct relative pronoun for things:",
      ["who", "whose", "which", "where"],
      2, "'Which' (or 'that') for things and animals.", ["treasure-hunt"]),
    q("Complete: 'That's the café ___ we first met.'",
      ["who", "which", "where", "whose"],
      2, "'Where' for places.", ["treasure-hunt"]),
    q("Complete: 'Do you know the girl ___ father is a famous actor?'",
      ["who", "which", "where", "whose"],
      3, "'Whose' expresses possession (чей/чья/чьё).", ["treasure-hunt"]),
    # treasure-hunt — vocabulary
    q("What does 'relative clause' help us do?",
      ["ask a question", "add information about a noun", "make a negative", "talk about the future"],
      1, "Relative clauses add extra information about a noun.", ["treasure-hunt"]),
    q("Complete: 'I lost the necklace ___ my grandmother gave me.'",
      ["who", "where", "which", "whose"],
      2, "'Which' (or 'that') for a thing (necklace).", ["treasure-hunt"]),
]

# ─── DAY 12: pay-me-more + im-just-looking ─────────────────────────
DAY12 = [
    # pay-me-more — too much/many, enough, very
    q("Complete: 'There's ___ sugar in this cake.'",
      ["too many", "too much", "enough", "very"],
      1, "'Too much' + uncountable noun (sugar).", ["pay-me-more"]),
    q("Choose the correct sentence:",
      ["There are too many people in the room.", "There are too much people in the room.", "There is too many people.", "There are too much peoples."],
      0, "'Too many' + countable plural noun (people).", ["pay-me-more"]),
    q("Complete: 'We don't have ___ time.'",
      ["too much", "too many", "enough", "very"],
      2, "'Enough time' — 'достаточно времени'.", ["pay-me-more"]),
    q("Choose the correct sentence:",
      ["The soup is hot enough now.", "The soup is enough hot now.", "The soup hot enough.", "The soup is too hot enough."],
      0, "'Enough' comes AFTER adjectives: 'hot enough'.", ["pay-me-more"]),
    # pay-me-more — vocabulary
    q("What's the difference between 'too' and 'very'?",
      ["They are the same.", "'Too' means 'слишком (проблема)', 'very' means 'очень'.", "'Very' is stronger than 'too'.", "'Too' is positive, 'very' is negative."],
      1, "'Too' = excessively (negative). 'Very' = just 'very' (neutral).", ["pay-me-more"]),
    q("Complete: 'I'm very tired, but not ___ tired to go for a walk.'",
      ["too", "so", "enough", "very"],
      0, "'Not too tired' — 'не настолько устал, чтобы...'.", ["pay-me-more"]),
    # im-just-looking — Buying things
    q("What does a shop assistant typically ask?",
      ["What do you want?", "Can I help you?", "You need something?", "How much is it?"],
      1, "'Can I help you?' is the standard shop assistant greeting.", ["im-just-looking"]),
    q("Complete: 'How much is this ___?'",
      ["dress", "cost", "price", "money"],
      0, "'How much is this dress?' — asking the price of an item.", ["im-just-looking"]),
    q("What do you say when you want to return something?",
      ["I'll take it.", "I'd like a refund, please.", "Can I try this on?", "I'm just looking."],
      1, "'I'd like a refund' means 'я хотел бы вернуть деньги'.", ["im-just-looking"]),
    q("Complete: 'Can I ___ this on?'",
      ["take", "try", "wear", "get"],
      1, "'Try on' — 'примерить' (clothes).", ["im-just-looking"]),
    # im-just-looking — vocabulary
    q("What does 'I'm just looking' mean?",
      ["Я просто смотрю (не нужна помощь)", "Я ищу что-то конкретное", "Я хочу купить", "Я жду"],
      0, "'I'm just looking' = 'я просто смотрю, помощь не нужна'.", ["im-just-looking"]),
    q("Complete: 'Do you have this jacket ___ black?'",
      ["on", "in", "at", "by"],
      1, "'In black' — 'в чёрном цвете'.", ["im-just-looking"]),
]

# ─── DAY 13: green-living + into-the-wild ──────────────────────────
DAY13 = [
    # green-living — Comparatives and superlatives
    q("Complete: 'My new car is ___ than my old one.'",
      ["fast", "faster", "fastest", "more fast"],
      1, "Short adjective (fast) + -er + than.", ["green-living"]),
    q("Choose the correct comparative:",
      ["This exercise is more difficult than the last one.", "This exercise is difficulter than.", "This is more easy than.", "This exercise is difficulter."],
      0, "Long adjective (difficult) → 'more difficult + than'.", ["green-living"]),
    q("Complete: 'She is ___ most talented musician in the band.'",
      ["a", "an", "the", "—"],
      2, "'The' + superlative: 'the most talented'.", ["green-living"]),
    q("Choose the correct sentence:",
      ["This phone is not as expensive as that one.", "This phone is not as expensive than that one.", "This phone is more cheap as that one.", "This phone is as expensive not."],
      0, "'Not as...as' — 'не такой... как'.", ["green-living"]),
    # green-living — vocabulary
    q("Complete: 'The best way to learn a language is to ___ every day.'",
      ["practise", "practice", "practising", "practised"],
      0, "'Practise' (verb) — 'практиковаться'.", ["green-living"]),
    q("What are the three irregular comparative/superlative exceptions?",
      ["good/better/best, bad/worse/worst, far/further/furthest", "good/gooder/goodest, bad/badder/baddest", "nice/nicer/nicest, big/bigger/biggest", "happy/happier/happiest, easy/easier/easiest"],
      0, "The three key irregular sets: good→better→best, bad→worse→worst, far→further→furthest.", ["green-living"]),
    # into-the-wild — Articles
    q("Complete: 'I saw ___ bird in the garden.'",
      ["a", "an", "the", "—"],
      0, "'A' — first mention of something, before consonant sound.", ["into-the-wild"]),
    q("Choose the correct sentence:",
      ["The sun rises in the east.", "A sun rises in an east.", "Sun rises in east.", "The sun rises in an east."],
      0, "'The' with unique things (sun, east).", ["into-the-wild"]),
    q("Complete: '___ dogs need exercise every day.' (in general)",
      ["The", "A", "An", "—"],
      3, "No article with plural nouns in general sense.", ["into-the-wild"]),
    q("Choose the correct sentence:",
      ["I went to the park near my house.", "I went to park near my house.", "I went to a park near my house.", "I went to an park."],
      0, "'The' — specific park (the one near my house).", ["into-the-wild"]),
    # into-the-wild — vocabulary
    q("When do we use 'an' instead of 'a'?",
      ["before consonant sounds", "before vowel sounds", "before plural nouns", "always"],
      1, "'An' before vowel sounds: an apple, an hour.", ["into-the-wild"]),
    q("Complete: '___ elephant can live for 70 years.'",
      ["A", "An", "The", "—"],
      1, "'An elephant' — 'an' before vowel sound.", ["into-the-wild"]),
]

# ─── DAY 14: it-could-be-because + top-cities ─────────────────────
DAY14 = [
    # it-could-be-because — Making guesses (must, might, could, can't)
    q("Complete: 'You've been travelling all day — you ___ be exhausted!'",
      ["can't", "must", "might", "could"],
      1, "'Must' — logical deduction (95% sure).", ["it-could-be-because"]),
    q("Choose the correct sentence for a negative deduction:",
      ["That can't be John — he's on holiday in Spain.", "That mustn't be John.", "That might not be John.", "That isn't be John."],
      0, "'Can't' = уверенность, что это НЕ так.", ["it-could-be-because"]),
    q("Complete: 'I'm not sure where she is. She ___ be in the library.'",
      ["must", "can't", "might", "will"],
      2, "'Might' — possibility (~50%).", ["it-could-be-because"]),
    q("What's the difference between 'may' and 'might' for deductions?",
      ["May is more formal, might is less certain.", "May is past tense.", "Might is only for negative.", "They mean exactly the same."],
      0, "'May' is slightly more formal/confident than 'might'.", ["it-could-be-because"]),
    # it-could-be-because — vocabulary
    q("Complete: 'The ground is wet. It ___ have rained.'",
      ["must", "can't", "might", "could"],
      0, "'Must have rained' — logical deduction about the past.", ["it-could-be-because"]),
    q("What does 'deduction' mean in this context?",
      ["обман", "вычет", "догадка / логический вывод", "вычитание"],
      2, "'Deduction' here means 'догадка / логический вывод'.", ["it-could-be-because"]),
    # top-cities — Uses of like
    q("Complete: 'What ___ your city like?'",
      ["does", "is", "does it", "—"],
      1, "'What is...like?' — asking for a description.", ["top-cities"]),
    q("Choose the correct question about appearance:",
      ["What does he look like?", "What is he like?", "What does he like?", "How does he look?"],
      0, "'What does he look like?' asks about physical appearance.", ["top-cities"]),
    q("Complete: 'I'd like ___ visit Tokyo one day.'",
      ["to", "—", "for", "that"],
      0, "'I'd like to' + verb — expressing a wish.", ["top-cities"]),
    q("What does 'What's it like living in a big city?' ask about?",
      ["the cost of living", "the experience of living there", "the location", "the size"],
      1, "'What's it like...?' asks about the experience or impression.", ["top-cities"]),
    # top-cities — vocabulary
    q("Complete: 'I like ___ around old towns.'",
      ["walk", "walked", "walking", "to walking"],
      2, "'Like + -ing' — expressing enjoyment of an activity.", ["top-cities"]),
    q("What does 'He is like his father' mean?",
      ["Он похож на отца (по характеру)", "Он любит отца", "Он выглядит как отец", "Он хочет быть как отец"],
      0, "'He is like his father' — describes character, not appearance.", ["top-cities"]),
]

# ─── DAY 15: crime-and-punishment + theres-a-problem ──────────────
DAY15 = [
    # crime-and-punishment — Passive voice
    q("Complete: 'Thousands of phones ___ every day in big cities.'",
      ["are stolen", "steal", "are stealing", "is stolen"],
      0, "Present passive: 'are + V3' (are stolen).", ["crime-and-punishment"]),
    q("Choose the correct passive sentence:",
      ["The thieves were arrested a few hours after the robbery.", "The thieves arrested a few hours after.", "The thieves was arrested.", "The thiefs were arrested."],
      0, "Past passive: 'were + V3' (were arrested).", ["crime-and-punishment"]),
    q("Complete: 'This museum ___ in 1890.'",
      ["built", "was built", "was builded", "is built"],
      1, "'Was built' — past passive, 'был построен'.", ["crime-and-punishment"]),
    q("When do we use the passive voice?",
      ["When the action is more important than who did it.", "When we know exactly who did it.", "Only in present tense.", "Only with irregular verbs."],
      0, "Passive is used when the action is more important than the doer.", ["crime-and-punishment"]),
    # crime-and-punishment — vocabulary
    q("Complete: 'The cake was made ___ my grandmother.'",
      ["from", "by", "of", "with"],
      1, "'By' introduces the agent in passive sentences.", ["crime-and-punishment"]),
    q("What does 'suspect' mean in a crime context?",
      ["полицейский", "подозреваемый", "преступник", "свидетель"],
      1, "'Suspect' = 'подозреваемый'.", ["crime-and-punishment"]),
    # theres-a-problem — Complaining
    q("Complete the polite complaint: 'I'm sorry to bother you, but the air conditioner ___ working.'",
      ["isn't", "doesn't", "won't", "hasn't"],
      0, "'Isn't working' — present continuous for a current problem.", ["theres-a-problem"]),
    q("Choose the correct polite complaint opening:",
      ["I'm afraid there's a problem with my order.", "There is problem.", "You have a problem.", "This is bad."],
      0, "'I'm afraid there's a problem...' is a polite way to start a complaint.", ["theres-a-problem"]),
    q("Complete: 'Could you please ___ the bill? There's a mistake.'",
      ["check", "to check", "checking", "checked"],
      0, "'Could you please check' — base verb after 'could you please'.", ["theres-a-problem"]),
    q("What is the 'politeness sandwich' for complaints?",
      ["Problem + request + goodbye", "Politeness opener + problem + polite request", "Just the problem", "Accusation + demand"],
      1, "Start with 'I'm sorry / I'm afraid', state the problem, end with 'Could you...'.", ["theres-a-problem"]),
    # theres-a-problem — vocabulary
    q("Complete: 'There seems to be a problem ___ the Wi-Fi connection.'",
      ["with", "in", "on", "at"],
      0, "'A problem with' — correct preposition.", ["theres-a-problem"]),
    q("What does 'I'm afraid' in a complaint express?",
      ["actual fear", "politeness / softening the complaint", "anger", "surprise"],
      1, "'I'm afraid' softens the complaint — it doesn't mean actual fear.", ["theres-a-problem"]),
]

# ─── DAY 16: keeping-in-touch + make-a-difference ──────────────────
DAY16 = [
    # keeping-in-touch — Present perfect (just, already, yet)
    q("Complete: 'Have you ever ___ sushi?'",
      ["try", "tried", "trying", "tries"],
      1, "'Have you tried' — present perfect with 'ever' for experience.", ["keeping-in-touch"]),
    q("Choose the correct sentence:",
      ["I haven't replied to his message yet.", "I haven't replied to his message already.", "I not replied yet.", "I haven't reply yet."],
      0, "'Yet' in negative sentences — 'ещё не'.", ["keeping-in-touch"]),
    q("Complete: 'She has ___ sent the email.' (already)",
      ["just", "yet", "already", "never"],
      2, "'Already' — 'уже' (in affirmative sentences).", ["keeping-in-touch"]),
    q("Complete: 'We've ___ got back from holiday.' (just now)",
      ["just", "already", "yet", "ever"],
      0, "'Just' — 'только что'.", ["keeping-in-touch"]),
    # keeping-in-touch — vocabulary
    q("What does 'present perfect' connect?",
      ["the past with the present", "only the past", "only the present", "the future"],
      0, "Present perfect connects past actions/experiences to the present moment.", ["keeping-in-touch"]),
    q("Complete: 'I haven't done it ___ .'",
      ["yet", "already", "just", "ever"],
      0, "'Yet' in negative sentences, at the end.", ["keeping-in-touch"]),
    # make-a-difference — Real conditionals & time clauses
    q("Complete: 'If I ___ hard, I'll pass the exam.'",
      ["study", "will study", "studied", "am studying"],
      0, "In 'if' clauses, use present simple (not 'will').", ["make-a-difference"]),
    q("Choose the correct sentence:",
      ["I'll call you when I arrive at the station.", "I'll call you when I will arrive.", "I call you when I'll arrive.", "I'll call you when I arrived."],
      0, "'When' + present simple (not 'will') for future time clauses.", ["make-a-difference"]),
    q("Complete: 'As soon as I ___ home, I'll send you the documents.'",
      ["get", "will get", "got", "am getting"],
      0, "'As soon as' + present simple for future.", ["make-a-difference"]),
    q("Complete: 'We won't start the meeting ___ everyone arrives.'",
      ["until", "when", "as soon as", "if"],
      0, "'Until' — 'пока не'.", ["make-a-difference"]),
    # make-a-difference — vocabulary
    q("What does 'real conditional' describe?",
      ["imaginary situations", "real possible situations in the future", "past events", "unreal situations"],
      1, "Real conditionals describe real possible situations.", ["make-a-difference"]),
    q("Complete: 'I'll finish this ___ I go out.'",
      ["before", "until", "after", "when"],
      0, "'Before' + present simple for time clause.", ["make-a-difference"]),
]

# ─── DAY 17: i-totally-disagree + caught-on-film ──────────────────
DAY17 = [
    # i-totally-disagree — Giving opinions
    q("Complete: '___ my opinion, smartphones have changed communication.'",
      ["On", "In", "At", "By"],
      1, "'In my opinion' — correct preposition.", ["i-totally-disagree"]),
    q("Choose the polite disagreement:",
      ["I'm not sure about that.", "You're wrong.", "That's terrible.", "No, you're incorrect."],
      0, "'I'm not sure about that' is polite disagreement.", ["i-totally-disagree"]),
    q("Complete: '___ totally agree — that app is incredibly useful.'",
      ["I'm", "I", "Me", "My"],
      1, "'I totally agree' — correct form.", ["i-totally-disagree"]),
    q("What does 'That's a good point, but...' express?",
      ["complete agreement", "agreement + counterargument", "disagreement", "uncertainty"],
      1, "'That's a good point, but...' acknowledges the other person's view then offers a different perspective.", ["i-totally-disagree"]),
    # i-totally-disagree — vocabulary
    q("Complete: 'I ___ with that statement.'",
      ["disagree", "disagreement", "disagreeing", "disagreed"],
      0, "'I disagree' — present simple, verb.", ["i-totally-disagree"]),
    q("What does 'pros and cons' mean?",
      ["профессионалы и консультанты", "плюсы и минусы", "до и после", "за и против"],
      1, "'Pros and cons' = 'плюсы и минусы'.", ["i-totally-disagree"]),
    # caught-on-film — Reported speech
    q("Complete: 'He said he ___ really nervous before the audition.'",
      ["is", "was", "has been", "will be"],
      1, "In reported speech, present shifts to past: 'is' → 'was'.", ["caught-on-film"]),
    q("Choose the correct reported speech:",
      ["She told me she had never been to a film premiere.", "She told me she never went.", "She told me she has never been.", "She told me she didn't be."],
      0, "'Have never been' → 'had never been' (backshift).", ["caught-on-film"]),
    q("Complete: 'They asked if I ___ seen the director's latest movie.'",
      ["have", "had", "did", "was"],
      1, "'Have seen' → 'had seen' (backshift in reported question).", ["caught-on-film"]),
    q("What's the difference between 'say' and 'tell'?",
      ["They are the same.", "'Tell' needs an object (tell someone), 'say' doesn't.", "'Say' needs an object.", "Tell is past tense of say."],
      1, "'Tell' + person: 'He told me'. 'Say' + (that) clause: 'He said (that)...'.", ["caught-on-film"]),
    # caught-on-film — vocabulary
    q("Complete: 'The actor said he would sign ___ after the show.'",
      ["autographs", "signs", "signatures", "signing"],
      0, "'Sign autographs' — 'раздавать автографы'.", ["caught-on-film"]),
    q("What happens to 'will' in reported speech?",
      ["stays 'will'", "changes to 'would'", "changes to 'could'", "changes to 'can'"],
      1, "'Will' changes to 'would' in reported speech.", ["caught-on-film"]),
]

# ─── DAY 18: a-lucky-break + what-can-i-do-for-you ─────────────────
DAY18 = [
    # a-lucky-break — Second conditional
    q("Complete: 'If I ___ famous, I would hate the paparazzi.'",
      ["am", "will be", "were", "was"],
      2, "'If I were' — subjunctive 'were' for all persons in second conditional.", ["a-lucky-break"]),
    q("Choose the correct second conditional sentence:",
      ["If she had more free time, she could take acting classes.", "If she has more free time, she could take acting classes.", "If she will have more time, she could take classes.", "If she had more time, she will take classes."],
      0, "Second conditional: 'If + past simple, would/could + verb'.", ["a-lucky-break"]),
    q("Complete: 'What ___ you do if you met your favourite actor?'",
      ["will", "would", "do", "are"],
      1, "'What would you do' — second conditional question.", ["a-lucky-break"]),
    q("What's the difference between first and second conditional?",
      ["First is about the past, second about the future.", "First is real/possible, second is unreal/imaginary.", "First uses 'would', second uses 'will'.", "They are the same."],
      1, "First conditional: real possibility (if + present, will). Second: unreal/imaginary (if + past, would).", ["a-lucky-break"]),
    # a-lucky-break — vocabulary
    q("Complete: 'If I could act, I would ___ to get a role in Hollywood.'",
      ["try", "tried", "trying", "tries"],
      0, "After 'would', use base verb: 'would try'.", ["a-lucky-break"]),
    q("What does 'paparazzi' mean?",
      ["папарацци (назойливые фотографы знаменитостей)", "поклонники", "телохранители", "репортёры"],
      0, "'Paparazzi' = 'папарацци'.", ["a-lucky-break"]),
    # what-can-i-do-for-you — Requests and offers
    q("Complete: '___ you possibly help me with this report?'",
      ["Can", "Could", "Will", "Do"],
      1, "'Could you possibly...?' — very polite request.", ["what-can-i-do-for-you"]),
    q("Choose the correct offer: '___ you like me to call a taxi?'",
      ["Do", "Would", "Could", "Will"],
      1, "'Would you like me to...?' — polite offer.", ["what-can-i-do-for-you"]),
    q("Complete: 'I'll ___ the door for you.' (offering help)",
      ["getting", "to get", "get", "got"],
      2, "'I'll + base verb' for spontaneous offers.", ["what-can-i-do-for-you"]),
    q("What does 'Shall I make some tea?' mean?",
      ["Я обязательно сделаю чай.", "Может, мне заварить чай?", "Ты будешь чай?", "Чай готов."],
      1, "'Shall I...?' offers to do something for someone.", ["what-can-i-do-for-you"]),
    # what-can-i-do-for-you — vocabulary
    q("Complete: 'Would you mind ___ for a few minutes?'",
      ["wait", "to wait", "waiting", "waited"],
      2, "'Would you mind + -ing' — polite request.", ["what-can-i-do-for-you"]),
    q("What does 'lend a hand' mean?",
      ["дать руку", "помочь", "одолжить", "взять за руку"],
      1, "'Lend a hand' = 'помочь'.", ["what-can-i-do-for-you"]),
]

# ─── DAY 19: Unit 1 — Life (review) ───────────────────────────────
DAY19 = [
    q("Complete: 'What ___ you do last weekend?'",
      ["do", "did", "does", "are"],
      1, "'What did you do' — past simple question.", ["true-love"]),
    q("Choose the correct sentence:",
      ["I met my wife at university in 2010.", "I meeted my wife at university.", "I was meeting my wife at university.", "I have met my wife at university in 2010."],
      0, "'Met' is the past simple of 'meet' — used with specific past time.", ["true-love"]),
    q("Which is a correct subject question?",
      ["Who lives in that big house?", "Who does live in that big house?", "Who do live in that big house?", "Who living in that big house?"],
      0, "Subject question — no auxiliary needed.", ["relax", "feeling-good"]),
    q("Complete: 'She is usually cheerful, but today she ___ a bit grumpy.'",
      ["feels", "is feeling", "feel", "feeling"],
      1, "Present continuous for today's unusual state.", ["nice-day"]),
    q("Which sentence is NOT correct?",
      ["I am knowing the answer.", "I know the answer.", "She wants a new job.", "He loves his work."],
      0, "'Know' is a state verb, cannot be used in continuous.", ["the-company-4u"]),
    q("Complete: 'I always ___ coffee in the morning.'",
      ["drink", "am drinking", "drinking", "drinks"],
      0, "'Always' + present simple for routine.", ["risky-business"]),
    q("What does 'I don't mind commuting' mean?",
      ["Обожаю ездить на работу.", "Не против добираться до работы.", "Ненавижу дорогу.", "Никогда не езжу на работу."],
      1, "'Don't mind' = 'не против'.", ["like-working-outside"]),
    q("Complete the phrase: 'Hey, long time no see! How ___ things?'",
      ["do", "are", "is", "does"],
      1, "'How are things?' — informal greeting.", ["feeling-good"]),
    q("Choose the correct collocation: 'We had a ___ in the garden last Sunday.'",
      ["barbecue", "barbecue party", "barbecuing", "barbecued"],
      0, "'Have a barbecue' — fixed collocation.", ["feeling-good"]),
    q("Complete: 'My family ___ board games every Friday night.'",
      ["plays", "play", "is playing", "are playing"],
      0, "Third person singular: 'plays' (family = collective, but usually singular in BrE).", ["feeling-good"]),
    q("Which sentence is correct?",
      ["I'm usually going to bed at 11.", "I usually go to bed at 11.", "I go usually to bed at 11.", "Usually I go to bed at 11."],
      1, "Adverb of frequency before main verb: 'usually go'.", ["risky-business"]),
    q("Complete: 'I can't stand people who are always ___ for meetings.'",
      ["late", "later", "latest", "lately"],
      0, "'Be late for' — 'опаздывать на'.", ["like-working-outside"]),
]

# ─── DAY 20: Unit 2 — Work (review) ────────────────────────────────
DAY20 = [
    q("Complete: 'A sales rep usually ___ a lot for work.'",
      ["travel", "travels", "travelling", "travelled"],
      1, "Third person + 's' in present simple.", ["risky-business"]),
    q("Choose the correct adverb position: 'She ___ rarely stressed.'",
      ["is", "does", "has", "rarely is"],
      0, "Adverb of frequency after 'be'.", ["risky-business"]),
    q("Complete: 'I ___ working for a big company.'",
      ["enjoy", "enjoy to", "enjoying", "am enjoy"],
      0, "'Enjoy' + -ing form.", ["like-working-outside"]),
    q("Choose the strongest dislike:",
      ["I don't like working late.", "I can't stand working in an open-plan office.", "I don't mind working late.", "I'm not keen on working late."],
      1, "'Can't stand' is the strongest dislike.", ["like-working-outside"]),
    q("What does 'not my cup of tea' mean?",
      ["не моё, не по душе", "очень люблю", "в самый раз", "это мой любимый чай"],
      0, "'Not my cup of tea' = 'не моё, не по душе'.", ["like-working-outside"]),
    q("Complete: 'This ___ to the company.'",
      ["is belonging", "belongs", "belong", "is belong"],
      1, "'Belongs' — state verb.", ["the-company-4u"]),
    q("Which sentence is correct?",
      ["She is having lunch with a client today.", "She is having a car.", "She is knowing the answer.", "She is wanting a new job."],
      0, "'Have' as an action (have lunch) can be continuous. 'Have' as state (have a car) cannot.", ["the-company-4u"]),
    q("Complete: 'Could you ___ me a favour?'",
      ["make", "do", "have", "take"],
      1, "'Do someone a favour' — fixed collocation.", ["hidden-talent", "the-company-4u"]),
    q("Complete: 'I ___ a decision about which course to take.'",
      ["make", "do", "have", "take"],
      0, "'Make a decision' — fixed collocation.", ["hidden-talent"]),
    q("What does 'work remotely' mean?",
      ["работать в офисе", "работать удалённо", "работать сверхурочно", "работать в команде"],
      1, "'Work remotely' = 'работать удалённо'.", ["risky-business"]),
    q("Complete: 'I don't ___ working late sometimes.'",
      ["mind", "matter", "care", "like"],
      0, "'Don't mind + -ing' = neutral about it.", ["like-working-outside"]),
    q("Which adverb of frequency means 0%?",
      ["always", "usually", "often", "never"],
      3, "'Never' = 0% frequency.", ["risky-business"]),
]

# ─── DAY 21: Unit 3 — Time Out (review) ────────────────────────────
DAY21 = [
    q("Complete: 'I ___ sightseeing tomorrow — I've booked a tour.'",
      ["am going", "will go", "go", "might go"],
      0, "Present continuous for a definite future arrangement.", ["free-in-nyc"]),
    q("Choose the correct sentence about a plan without definite details:",
      ["We are going to have a picnic in Central Park this Sunday.", "We are having a picnic at 3pm — table booked.", "We have a picnic.", "We will have a picnic right now."],
      0, "'Be going to' for intention without confirmed details.", ["free-in-nyc"]),
    q("Complete: '___ happened at the skate park yesterday?'",
      ["What", "What did", "What was", "What does"],
      0, "Subject question — no auxiliary needed.", ["relax"]),
    q("Which is an object question?",
      ["Who called you?", "Who did you call?", "Who lives here?", "What happened?"],
      1, "'Who did you call?' — 'who' is the object, auxiliary needed.", ["relax", "feeling-good"]),
    q("Complete on the phone: 'Hello, ___ is Anna speaking.'",
      ["this", "that", "here", "it's"],
      0, "'This is Anna speaking' — phone introduction.", ["can-i-take-a-message"]),
    q("What does 'hold on' mean on the phone?",
      ["повесить трубку", "подождать", "перезвонить", "записать"],
      1, "'Hold on' = 'подождите (не вешайте трубку)'.", ["can-i-take-a-message"]),
    q("Complete: 'Could I ___ to Mr Jones, please?'",
      ["tell", "speak", "say", "talk"],
      1, "'Could I speak to...' — polite phone request.", ["can-i-take-a-message"]),
    q("Complete: 'Have you ever ___ on stage?'",
      ["perform", "performed", "performing", "performs"],
      1, "'Have you ever + V3' (performed).", ["hidden-talent"]),
    q("Choose the correct sentence:",
      ["I have never sung in public.", "I haven't never sung.", "I never sung.", "I didn't never sing."],
      0, "'Have never + V3' — one negative only.", ["hidden-talent"]),
    q("Complete: 'I need to ___ a decision.'",
      ["make", "do", "take", "have"],
      0, "'Make a decision' — fixed collocation.", ["hidden-talent"]),
    q("Complete: 'Please don't ___ a noise — the baby is sleeping.'",
      ["do", "make", "have", "take"],
      1, "'Make a noise' — fixed collocation.", ["hidden-talent"]),
    q("Complete: 'She has never ___ in a helicopter.'",
      ["fly", "flown", "flew", "flying"],
      1, "'Has never flown' — irregular past participle of 'fly'.", ["hidden-talent"]),
]

# ─── DAY 22: Unit 4 — Great Minds (review) ─────────────────────────
DAY22 = [
    q("Complete: 'You ___ wear a uniform at this school.' (obligation)",
      ["can", "have to", "mustn't", "don't have to"],
      1, "'Have to' — external obligation.", ["schools-of-thought"]),
    q("What does 'You mustn't use your phone during the exam' mean?",
      ["Ты не обязан пользоваться телефоном.", "Нельзя пользоваться телефоном.", "Ты можешь пользоваться телефоном.", "Телефон не нужен."],
      1, "'Mustn't' = строгий запрет.", ["schools-of-thought"]),
    q("Complete: 'You ___ borrow books from the library.' (permission)",
      ["must", "can", "have to", "mustn't"],
      1, "'Can' — разрешение.", ["schools-of-thought"]),
    q("Complete: 'We ___ go to school on Saturdays — it's optional.'",
      ["mustn't", "don't have to", "can't", "shouldn't"],
      1, "'Don't have to' = 'не обязательно'.", ["schools-of-thought"]),
    q("Choose the correct advice:",
      ["You should practise speaking every day.", "You should to practise.", "You should practising.", "You are should practise."],
      0, "'Should + base verb' — giving advice.", ["what-should-i-do"]),
    q("Complete: 'Why ___ you join a language exchange group?'",
      ["don't", "do", "aren't", "won't"],
      0, "'Why don't you...' — friendly suggestion.", ["what-should-i-do"]),
    q("Complete: 'If I ___ you, I'd start preparing earlier.'",
      ["am", "were", "was", "be"],
      1, "'If I were you' — fixed expression for giving advice.", ["what-should-i-do"]),
    q("Which verb takes the -ing form?",
      ["want", "need", "avoid", "plan"],
      2, "'Avoid' + -ing. Want, need, plan take 'to + verb'.", ["travel-tips"]),
    q("Complete: 'You ought ___ see a doctor.'",
      ["to", "—", "for", "that"],
      0, "'Ought to' + verb (same meaning as 'should').", ["what-should-i-do"]),
    q("Complete: 'Have you ever ___ a poem?'",
      ["write", "wrote", "written", "writing"],
      2, "'Have you ever written' — past participle of 'write'.", ["hidden-talent"]),
    q("Choose the correct sentence:",
      ["You can borrow books from the library for two weeks.", "You must borrow books.", "You don't have to borrow books.", "You can't borrow books."],
      0, "Permission statement.", ["schools-of-thought"]),
    q("What does 'ought to' express?",
      ["запрет", "совет (чуть более формально, чем should)", "разрешение", "возможность"],
      1, "'Ought to' expresses advice, slightly more formal than 'should'.", ["what-should-i-do"]),
]

# ─── DAY 23: Unit 5 — Travel (review) ──────────────────────────────
DAY23 = [
    q("Complete: 'I was travelling around Italy when I ___ my best friend.'",
      ["met", "was meeting", "have met", "meet"],
      0, "Past simple for the main event interrupting a continuous action.", ["fantastic-film-trips"]),
    q("Choose the correct sentence:",
      ["While we were driving to the coast, it started to rain.", "While we drove, it was starting to rain.", "While we were driving, it was raining.", "While we drive, it starts to rain."],
      0, "Past continuous (background) + past simple (interrupting event).", ["fantastic-film-trips"]),
    q("Complete: 'She ___ on the train when the inspector woke her.'",
      ["slept", "was sleeping", "has slept", "sleeps"],
      1, "Past continuous for ongoing background action.", ["fantastic-film-trips"]),
    q("Complete: 'I want ___ Japan next spring.'",
      ["visit", "to visit", "visiting", "visited"],
      1, "'Want to + verb'.", ["travel-tips"]),
    q("Complete: 'She enjoys ___ local food when she travels.'",
      ["try", "to try", "trying", "tried"],
      2, "'Enjoy + -ing'.", ["travel-tips"]),
    q("Complete: 'Go straight ___ until you see a supermarket.'",
      ["on", "in", "to", "at"],
      0, "'Go straight on' — directions.", ["you-cant-miss-it"]),
    q("What does 'You can't miss it!' mean?",
      ["Ты не сможешь это не заметить.", "Ты можешь пропустить.", "Это легко потерять.", "Ты не умеешь пропускать."],
      0, "'You can't miss it!' = 'не пройдёшь мимо!'.", ["you-cant-miss-it"]),
    q("Complete: 'The museum is ___ the train station.' (across from)",
      ["next", "opposite", "between", "on"],
      1, "'Opposite' = 'напротив'.", ["you-cant-miss-it"]),
    q("Complete: 'I suggest ___ a guided tour.'",
      ["take", "to take", "taking", "took"],
      2, "'Suggest + -ing'.", ["travel-tips"]),
    q("What does 'book in advance' mean?",
      ["отменить бронь", "забронировать заранее", "заплатить на месте", "проверить"],
      1, "'Book in advance' = 'бронировать заранее'.", ["travel-tips"]),
    q("Complete: '___ me, how do I get to the station?'",
      ["Excuse", "Sorry", "Pardon", "Forgive"],
      0, "'Excuse me' — polite way to start asking for directions.", ["you-cant-miss-it"]),
    q("Complete: 'Take the first ___ on the right.'",
      ["turning", "turn", "turned", "turns"],
      0, "'Take the first turning on the right' — standard direction.", ["you-cant-miss-it"]),
]

# ─── DAY 24: Unit 6 — Fitness (review) ─────────────────────────────
DAY24 = [
    q("Complete: 'I've been a vegetarian ___ five years.'",
      ["since", "for", "from", "ago"],
      1, "'For' + duration.", ["keeping-fit"]),
    q("Complete: 'She's worked at this gym ___ 2020.'",
      ["since", "for", "from", "in"],
      0, "'Since' + specific point in time.", ["keeping-fit"]),
    q("Complete: 'How long have you ___ your best friend?'",
      ["knew", "known", "know", "knowing"],
      1, "'Have known' — V3 (past participle) of 'know'.", ["keeping-fit"]),
    q("Complete: 'I ___ be 30 next year.'",
      ["will", "may", "might", "am"],
      0, "'Will' for certain future fact.", ["the-future-of-food"]),
    q("Which sentence expresses possibility (50%)?",
      ["It may rain later.", "It will rain.", "It can't rain.", "It is raining."],
      0, "'May' = 50% possibility.", ["the-future-of-food"]),
    q("Complete: 'I ___ try that new restaurant — I'm not sure yet.'",
      ["will", "might", "can't", "must"],
      1, "'Might' for low probability / uncertainty.", ["the-future-of-food"]),
    q("Complete: 'I've got a terrible ___ and my eyes hurt.'",
      ["headache", "head pain", "head hurt", "headache pain"],
      0, "'I've got a headache' — correct expression.", ["how-are-you-feeling"]),
    q("Complete: 'My throat ___ when I swallow.'",
      ["hurts", "hurt", "is hurting", "hurting"],
      0, "'My throat hurts' — simple present for current pain.", ["how-are-you-feeling"]),
    q("What does 'I feel dizzy' mean?",
      ["У меня болит голова", "У меня кружится голова", "Я плохо себя чувствую", "Я устал"],
      1, "'Dizzy' = 'головокружение'.", ["how-are-you-feeling"]),
    q("Complete: 'He's got a bad ___ and a runny nose.'",
      ["cough", "coughing", "coughs", "cough-up"],
      0, "'A cough' — noun.", ["how-are-you-feeling"]),
    q("Complete: 'I haven't seen him ___ we graduated.'",
      ["since", "for", "from", "ago"],
      0, "'Since' + event (graduation).", ["keeping-fit"]),
    q("Complete: 'In fifty years, we'll ___ eat lab-grown meat.'",
      ["probably", "maybe", "perhaps", "might"],
      0, "'Probably' after 'will' for likelihood.", ["the-future-of-food"]),
]

# ─── DAY 25: Unit 7 — Changes (review) ─────────────────────────────
DAY25 = [
    q("Complete: 'I ___ be afraid of the dark, but now I'm fine.'",
      ["used to", "use to", "was used to", "did use to"],
      0, "'Used to' — past state that no longer exists.", ["living-the-dream"]),
    q("Choose the correct negative: 'She ___ enjoy cooking, now she's a chef!'",
      ["didn't use to", "didn't used to", "used not", "not used to"],
      0, "Negative: 'didn't use to'.", ["living-the-dream"]),
    q("Complete the question: '___ you use to have long hair?'",
      ["Did", "Do", "Used", "Are"],
      0, "'Did you use to...?'", ["living-the-dream"]),
    q("Complete: 'I went to the library ___ study in peace.'",
      ["to", "for", "because", "so"],
      0, "'To + verb' for purpose.", ["the-great-impostor"]),
    q("Complete: 'She passed the exam ___ she worked hard.'",
      ["so", "to", "because", "because of"],
      2, "'Because' + clause for cause.", ["the-great-impostor"]),
    q("Complete: 'He forgot his keys, ___ he couldn't get in.'",
      ["because", "so", "to", "for"],
      1, "'So' for result.", ["the-great-impostor"]),
    q("Complete: 'I'll leave early so that I ___ miss the train.'",
      ["don't", "won't", "didn't", "wouldn't"],
      1, "'So that I won't miss' — purpose clause.", ["the-great-impostor"]),
    q("Complete: 'Could you tell me where the nearest bank ___?'",
      ["is", "it is", "does", "is it"],
      0, "Polite question: statement word order after 'could you tell me'.", ["can-you-tell-me"]),
    q("Complete: 'Do you know ___ there's a restaurant nearby?'",
      ["if", "that", "what", "where"],
      0, "'Do you know if...?' — yes/no question embedded.", ["can-you-tell-me"]),
    q("Complete: 'I'd like to know what time the museum ___ .'",
      ["opens", "does open", "open", "is opening"],
      0, "Statement word order after 'I'd like to know'.", ["can-you-tell-me"]),
    q("Complete: 'He used to ___, but he quit last year.'",
      ["smoke", "smoked", "smoking", "smokes"],
      0, "'Used to + base verb'.", ["living-the-dream"]),
    q("Complete: 'I was wondering ___ you could help me.'",
      ["if", "that", "what", "when"],
      0, "'I was wondering if' — very polite request.", ["can-you-tell-me"]),
]

# ─── DAY 26: Unit 8 — Money (review) ──────────────────────────────
DAY26 = [
    q("Complete: 'There's ___ sugar in this cake — it's too sweet.'",
      ["too many", "too much", "enough", "very"],
      1, "'Too much' + uncountable (sugar).", ["pay-me-more"]),
    q("Complete: 'There are ___ people in the room.'",
      ["too much", "too many", "too", "enough"],
      1, "'Too many' + countable (people).", ["pay-me-more"]),
    q("Complete: 'We don't have ___ chairs for everyone.'",
      ["too many", "enough", "too much", "very"],
      1, "'Enough chairs' — sufficient quantity.", ["pay-me-more"]),
    q("Choose the correct sentence:",
      ["The soup is hot enough now.", "The soup is enough hot.", "The soup is too enough hot.", "The soup is hot too much."],
      0, "'Enough' after adjectives: 'hot enough'.", ["pay-me-more"]),
    q("Complete: 'Can I ___ you?' — 'No thanks, I'm just looking.'",
      ["help", "ask", "assist", "serve"],
      0, "'Can I help you?' — shop assistant's greeting.", ["im-just-looking"]),
    q("Complete: 'How much ___ this dress?'",
      ["does", "is", "cost", "are"],
      1, "'How much is this...?' — asking price.", ["im-just-looking"]),
    q("Complete: 'I'd like a ___, please. This shirt is damaged.'",
      ["refund", "return", "exchange", "change"],
      0, "'I'd like a refund' — запрос возврата денег.", ["im-just-looking"]),
    q("Complete: 'Can I ___ this on?' (try clothes before buying)",
      ["take", "try", "wear", "put"],
      1, "'Try on' = 'примерить'.", ["im-just-looking"]),
    q("He's the guy ___ helped me with my homework.",
      ["who", "which", "where", "whose"],
      0, "'Who' for people in relative clauses.", ["treasure-hunt"]),
    q("That's the café ___ we first met.",
      ["who", "which", "where", "whose"],
      2, "'Where' for places.", ["treasure-hunt"]),
    q("Do you know the girl ___ father is a famous actor?",
      ["who", "which", "where", "whose"],
      3, "'Whose' for possession.", ["treasure-hunt"]),
    q("I lost the necklace ___ my grandmother gave me.",
      ["who", "which", "whose", "where"],
      1, "'Which' (or 'that') for things.", ["treasure-hunt"]),
]

# ─── DAY 27: Unit 9 — Nature (review) ─────────────────────────────
DAY27 = [
    q("Choose the correct comparative:",
      ["My new car is faster than my old one.", "My new car is more fast than my old one.", "My new car is fast than my old one.", "My new car is fastest than my old one."],
      0, "Short adjective 'fast' → 'faster + than'.", ["green-living"]),
    q("Complete: 'This exercise is ___ difficult than the last one.'",
      ["more", "most", "—", "er"],
      0, "Long adjective 'difficult' → 'more + difficult + than'.", ["green-living"]),
    q("Complete: 'She is ___ most talented musician in the band.'",
      ["a", "an", "the", "—"],
      2, "'The' + superlative.", ["green-living"]),
    q("Choose the correct sentence:",
      ["This phone is not as expensive as that one.", "This phone is not as expensive than that one.", "This phone is more cheap as that one.", "This phone is not so expensive than that one."],
      0, "'Not as...as' = 'не такой... как'.", ["green-living"]),
    q("Complete: 'I saw ___ bird in the garden.' (first mention)",
      ["a", "an", "the", "—"],
      0, "'A' for first mention.", ["into-the-wild"]),
    q("Complete: '___ sun rises in the east.'",
      ["A", "An", "The", "—"],
      2, "'The' with unique natural phenomena.", ["into-the-wild"]),
    q("Complete: '___ dogs need exercise every day.' (in general)",
      ["The", "A", "An", "—"],
      3, "No article with plural in general sense.", ["into-the-wild"]),
    q("Complete: 'The ground is wet. It ___ have rained.'",
      ["must", "can't", "might", "could"],
      0, "'Must have + V3' — logical deduction about the past.", ["it-could-be-because"]),
    q("Complete: 'That ___ be John — he's on holiday in Spain.'",
      ["must", "can't", "might", "could"],
      1, "'Can't' — уверенность, что это НЕ так.", ["it-could-be-because"]),
    q("Complete: 'She's not home. She ___ be at work.' (possibly)",
      ["must", "can't", "might", "will"],
      2, "'Might' for possibility.", ["it-could-be-because"]),
    q("Complete: 'What ___ your city like?'",
      ["does", "is", "are", "do"],
      1, "'What is...like?' — asking for description.", ["top-cities"]),
    q("Complete: 'What does he ___ like?' (appearance)",
      ["look", "be", "seem", "are"],
      0, "'What does he look like?' — external appearance.", ["top-cities"]),
]

# ─── DAY 28: Unit 10 — Society (review) ────────────────────────────
DAY28 = [
    q("Complete: 'Thousands of phones ___ every day in big cities.'",
      ["are stolen", "steal", "are stealing", "have stolen"],
      0, "Present passive: 'are + V3'.", ["crime-and-punishment"]),
    q("Choose the correct passive sentence:",
      ["The thieves were arrested a few hours after the robbery.", "The thieves arrested.", "The thieves was arrested.", "The thieves are arrested a few hours after."],
      0, "Past passive: 'were + V3'.", ["crime-and-punishment"]),
    q("Complete: 'This museum ___ in 1890.'",
      ["built", "was built", "builded", "is built"],
      1, "'Was built' — past passive.", ["crime-and-punishment"]),
    q("Complete: 'The cake was made ___ my grandmother.'",
      ["by", "from", "of", "with"],
      0, "'By' + agent in passive.", ["crime-and-punishment"]),
    q("Complete the complaint: 'I'm sorry to bother you, but the air conditioner ___ working.'",
      ["isn't", "doesn't", "won't", "hasn't"],
      0, "'Isn't working' — current problem.", ["theres-a-problem"]),
    q("Complete: 'I'm afraid ___ a problem with my order.'",
      ["it's", "there's", "that's", "this is"],
      1, "'There's a problem' — correct expression.", ["theres-a-problem"]),
    q("Complete: 'Could you please ___ the bill? There's a mistake.'",
      ["check", "to check", "checking", "checked"],
      0, "'Could you please + base verb'.", ["theres-a-problem"]),
    q("Complete: 'There seems to be a problem ___ the Wi-Fi.'",
      ["with", "in", "on", "at"],
      0, "'A problem with' — correct preposition.", ["theres-a-problem"]),
    q("Complete: 'This phone is not ___ expensive as that one.'",
      ["so", "as", "more", "too"],
      1, "'Not as...as' — comparison.", ["green-living"]),
    q("Choose the correct superlative:",
      ["She is the most talented musician.", "She is the more talented.", "She is the talentedest.", "She is a most talented."],
      0, "'The most + adj' — correct superlative for long adjectives.", ["green-living"]),
    q("Complete: 'A: The city is very crowded. B: I ___ not sure about that.'",
      ["am", "do", "have", "—"],
      0, "'I am not sure about that' — polite disagreement.", ["i-totally-disagree"]),
    q("Complete: 'The lights are off. They ___ be asleep.'",
      ["must", "can't", "might", "could"],
      0, "'Must be' — logical deduction.", ["it-could-be-because"]),
]

# ─── DAY 29: Unit 11 — Technology (review) ────────────────────────
DAY29 = [
    q("Complete: 'Have you ever ___ sushi?'",
      ["try", "tried", "trying", "tries"],
      1, "'Have you ever + V3'.", ["keeping-in-touch"]),
    q("Complete: 'I haven't replied to his message ___ .'",
      ["yet", "already", "just", "ever"],
      0, "'Yet' in negative sentences.", ["keeping-in-touch"]),
    q("Complete: 'She has ___ sent the email.' (уже)",
      ["already", "yet", "just", "ever"],
      0, "'Already' in affirmative sentences.", ["keeping-in-touch"]),
    q("Complete: 'We've ___ got back from holiday.' (только что)",
      ["just", "already", "yet", "ever"],
      0, "'Just' = 'только что'.", ["keeping-in-touch"]),
    q("Complete: 'If I ___ hard, I'll pass the exam.'",
      ["study", "will study", "studied", "would study"],
      0, "Present simple after 'if' in real conditional.", ["make-a-difference"]),
    q("Complete: 'I'll call you when I ___ at the station.'",
      ["arrive", "will arrive", "arrived", "am arriving"],
      0, "Present simple after 'when' in time clauses.", ["make-a-difference"]),
    q("Complete: 'As soon as I ___ home, I'll send the documents.'",
      ["get", "will get", "got", "am getting"],
      0, "Present simple after 'as soon as'.", ["make-a-difference"]),
    q("Complete: 'We won't start ___ everyone arrives.'",
      ["until", "when", "after", "before"],
      0, "'Until' = 'пока не'.", ["make-a-difference"]),
    q("Complete: '___ my opinion, smartphones have changed communication.'",
      ["In", "On", "At", "By"],
      0, "'In my opinion'.", ["i-totally-disagree"]),
    q("Complete: 'I ___ not sure about that.' (polite disagreement)",
      ["am", "do", "have", "will"],
      0, "'I am not sure about that' — polite disagreement.", ["i-totally-disagree"]),
    q("Choose the correct sentence:",
      ["I totally agree — that app is useful.", "I totally agreeing — that app is useful.", "I totally am agree.", "I totally agreed — that app is useful."],
      0, "'I totally agree' — correct form.", ["i-totally-disagree"]),
    q("Complete: '___ you ever tried Italian food?'",
      ["Have", "Did", "Do", "Are"],
      0, "'Have you ever' — present perfect for experience.", ["keeping-in-touch"]),
]

# ─── DAY 30: Unit 12 — Fame (review) ──────────────────────────────
DAY30 = [
    q("Complete: 'He said he ___ really nervous before the audition.'",
      ["is", "was", "has been", "will be"],
      1, "Backshift: 'is' → 'was' in reported speech.", ["caught-on-film"]),
    q("Complete: 'She told me she ___ never been to a film premiere.'",
      ["has", "had", "have", "will have"],
      1, "Backshift: 'have been' → 'had been'.", ["caught-on-film"]),
    q("Complete: 'They asked if I ___ seen the film.'",
      ["have", "had", "did", "was"],
      1, "'Have seen' → 'had seen'.", ["caught-on-film"]),
    q("Complete: 'If I ___ famous, I would hate the paparazzi.'",
      ["am", "were", "was", "will be"],
      1, "'If I were' — second conditional subjunctive.", ["a-lucky-break"]),
    q("Complete: 'If she ___ more free time, she could take acting classes.'",
      ["had", "has", "will have", "would have"],
      0, "Second conditional: 'If + past simple'.", ["a-lucky-break"]),
    q("Complete: 'What ___ you do if you met your favourite actor?'",
      ["will", "would", "do", "are"],
      1, "'Would' in the result clause of second conditional.", ["a-lucky-break"]),
    q("Complete: '___ you possibly help me with this report?'",
      ["Could", "Can", "Will", "Do"],
      0, "'Could you possibly' — polite request.", ["what-can-i-do-for-you"]),
    q("Complete: 'Would you like ___ to call a taxi?'",
      ["me", "I", "that", "—"],
      0, "'Would you like me to...' — polite offer.", ["what-can-i-do-for-you"]),
    q("Complete: 'I'll ___ the door for you.' (offering)",
      ["get", "getting", "to get", "got"],
      0, "'I'll + base verb' for spontaneous offers.", ["what-can-i-do-for-you"]),
    q("What does 'Shall I make some tea?' mean?",
      ["Ты сделаешь чай?", "Может, мне заварить чай?", "Чай уже готов.", "Я люблю чай."],
      1, "'Shall I...?' = 'Может, мне...?' — предложение помощи.", ["what-can-i-do-for-you"]),
    q("Complete: 'Would you mind ___ for a moment?'",
      ["wait", "waiting", "to wait", "waited"],
      1, "'Would you mind + -ing'.", ["what-can-i-do-for-you"]),
    q("Complete: 'The actor said he ___ sign autographs after the show.'",
      ["will", "would", "can", "must"],
      1, "'Will' → 'would' in reported speech.", ["caught-on-film"]),
]

# ─── ALL DAYS ───────────────────────────────────────────────────────
ALL_DAYS: list[list[dict]] = [
    DAY01, DAY02, DAY03, DAY04, DAY05, DAY06, DAY07, DAY08, DAY09, DAY10,
    DAY11, DAY12, DAY13, DAY14, DAY15, DAY16, DAY17, DAY18,
    DAY19, DAY20, DAY21, DAY22, DAY23, DAY24, DAY25, DAY26, DAY27, DAY28,
    DAY29, DAY30,
]


def main() -> None:
    TESTS.mkdir(parents=True, exist_ok=True)
    for i, day_questions in enumerate(ALL_DAYS, start=1):
        day_id = f"day-{i:02d}"
        path = TESTS / f"{day_id}.json"
        # Recompute IDs using the imported function
        for item in day_questions:
            item["id"] = compute_id(
                item["question"],
                item["options"],
                item["correctIndex"],
            )
        with open(path, "w", encoding="utf-8") as f:
            json.dump(day_questions, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"Written {path.name} — {len(day_questions)} questions")
    print(f"\nDone. Generated {len(ALL_DAYS)} test files.")


if __name__ == "__main__":
    main()
